field: 9767d245-69a9-444d-89ad-63c08cceeb3f # Ancilliary Item Information
fieldLayouts:
  324053be-7a23-4814-94d3-a2e3287e9b59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a77c9dcf-1b53-47f0-b94f-88b8dfcff3d5 # Add Additional Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cee868f-e833-418c-ac2f-96fa148a8073
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 895561aa-dd08-425b-bec2-414af42890c5
        userCondition: null
fields:
  a77c9dcf-1b53-47f0-b94f-88b8dfcff3d5: # Add Additional Info
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: addAdditionalInfo
    instructions: null
    name: 'Add Additional Info'
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''SuperTable''.'
      expectedType: SuperTable
      settings:
        __assoc__:
          0:
            - columns
            -
              55:
                __assoc__:
                  -
                    - width
                    - ''
              56:
                __assoc__:
                  -
                    - width
                    - ''
          1:
            - fieldLayout
            - row
          4:
            - selectionLabel
            - 'Add more info'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: additionalInformation
name: 'Additional Information'
sortOrder: 4
