field: 9767d245-69a9-444d-89ad-63c08cceeb3f # Ancilliary Item Information
fieldLayouts:
  e62de590-382c-4953-abe6-cd530058136a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 691a3baa-93ae-46a0-95e1-bf3e30a8262a # Item Drawing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5720f0-9d6c-4e40-b82b-7134d72248d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0dcef93-3f58-4ef6-a3b5-d19d96f503c1
        userCondition: null
fields:
  691a3baa-93ae-46a0-95e1-bf3e30a8262a: # Item Drawing
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemDrawing
    instructions: null
    name: 'Item Drawing'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:97f1d3a7-ddd4-4455-b3cd-927bbab12ae0' # Drawings
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:97f1d3a7-ddd4-4455-b3cd-927bbab12ae0' # Drawings
      restrictedLocationSubpath: null
      selectionLabel: 'Add a Drawing'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources:
        - 'volume:97f1d3a7-ddd4-4455-b3cd-927bbab12ae0' # Drawings
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: itemTechnicalDrawing
name: 'Item Technical Drawing'
sortOrder: 3
