field: 9767d245-69a9-444d-89ad-63c08cceeb3f # Ancilliary Item Information
fieldLayouts:
  330da277-ce8e-4180-b284-6075290f586f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: de6f38a7-4a16-4ec5-8f08-d8389d3308a5 # Data Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6559eaf9-2fa4-47a4-9c1b-d0e0a7d62301
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c423afc7-9198-4da6-afe4-b3a8780e38ad
        userCondition: null
fields:
  de6f38a7-4a16-4ec5-8f08-d8389d3308a5: # Data Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: dataTable
    instructions: null
    name: 'Data Table'
    searchable: true
    settings:
      columnsAddRowLabel: null
      columnsInstructions: null
      columnsLabel: 'Add Table Columns'
      enableAlignmentColumn: true
      enableWidthColumn: true
      rowsAddRowLabel: null
      rowsInstructions: null
      rowsLabel: 'Add Table Rows'
    translationKeyFormat: null
    translationMethod: none
    type: verbb\tablemaker\fields\TableMakerField
handle: itemDataTable
name: 'Item Data Table'
sortOrder: 5
