fieldLayouts:
  ea259485-abb3-47b8-af0b-50ccf300cfef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 12acd934-8c7d-4581-905b-8ee3fe93dc1d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 160c79fd-9ae2-4c48-bd9c-9b12ba6ff183
        userCondition: null
handle: default
name: Default
