color: null
description: null
fieldLayouts:
  324053be-7a23-4814-94d3-a2e3287e9b59:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: a77c9dcf-1b53-47f0-b94f-88b8dfcff3d5 # Ancilliary Item Information - Additional Information - Add Additional Info
            handle: null
            includeInCards: false
            instructions: null
            label: 'Add Additional Info'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0306e7c6-fe92-4045-91de-bba1ec064d4d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 895561aa-dd08-425b-bec2-414af42890c5
        userCondition: null
handle: additionalInformation
hasTitleField: false
icon: null
name: 'Additional Information'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
