fieldLayouts:
  709d6e8c-b656-43d7-b476-1e553790deb4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 423a579d-5ce9-447a-92a9-1736fb5eb208
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f59ecb5-fae8-4f30-9a78-e33390e299d5 # Text over map
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14ccac82-cfc3-4193-89c2-391b3881b65a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2f82710-6281-4b11-98e7-e554e53b8ec7 # Intro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c78aff8-6790-4ad1-b788-d1d1e0a1829d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a57a2ac4-34cb-4e08-81cd-a71df4f6458e # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33dba016-e5d0-4d9f-b44b-640840696656
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12098827-5de3-4901-9782-8be01b052435 # Expanded Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec6bede7-20ca-4ad9-a791-3e24ec1fdb83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64bab4c5-2431-415e-be4d-a9aad63b08aa # Secondary Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec960045-8d8a-4305-adb8-8c7a17291d34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d2eb001-baed-45eb-87fc-e2b99f2315d3 # Secondary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d75f0d2c-9410-4400-b6ce-f7331649d3ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e37206da-e6c5-43c7-b877-e0c8b494846a # Accreditations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bdf2e2b-78f5-47b6-92ac-c315e86932a4
            userCondition: null
            warning: null
            width: 100
        name: 'Company Background'
        uid: 33a12640-7922-4f61-93f4-d7d3f69fd922
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7acd5d39-6c1f-40f8-add1-7d3ff114c820 # Meta Title (if different from page title)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ebd00ac-3fa6-42aa-95e9-31d5b1141a08
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d5aae72-d3da-4be6-810d-6382928dd1fe # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b51229c-3e37-4316-be78-bee929684d71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e2808b9-d312-4282-8380-7b1d3f248e8b # Meta OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cbaae1a-2307-488c-8b71-9691d90b7893
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3f4ab15-88ea-4329-baa2-46cbe0eacca8 # Meta OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10e81f73-bf6b-41ba-b03e-3a55c1ff6e63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf4a664b-f40f-4d66-b727-a4ec3378e188 # Meta Twitter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 082cbc40-dcf4-485e-98d0-4805471d7194
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37064180-6b3f-4c01-994d-58da67c146c0 # Meta Twitter Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56bc0d26-d38f-4121-a434-39c4aec89929
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: c8881e82-8188-49cd-adcc-892e6047c632
        userCondition: null
handle: companyBackground
hasTitleField: false
name: 'Company Background'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
