fieldLayouts:
  db6a43fb-62e4-48ad-a1d0-0c76fe61d928:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec19dc5b-fe03-4485-898f-811d27a0d4a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b546229-8eda-467e-8b33-057f66334f83
        userCondition: null
handle: enquiries
hasTitleField: false
name: Enquiries
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
