color: null
description: null
fieldLayouts:
  26cf4905-20da-4750-a196-f004708b4ad2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 851fbe84-b848-4787-a77c-34cf932039f4
            handle: null
            includeInCards: true
            instructions: null
            label: 'Note Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 738c4f8f-64f9-4177-8270-08a430d6b588
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37d05d25-9f02-4fa4-a442-783a579e27a7
        userCondition: null
handle: fd_st_specialNotesBlock
hasTitleField: false
icon: null
name: 'Special Notes Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
