color: null
description: null
fieldLayouts:
  7e9c3ec5-7553-496a-88c3-e0e478b2c7f4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: e7ec919b-58eb-4d3f-a150-c232579f3653
            handle: dataTable
            includeInCards: false
            instructions: null
            label: 'Data Table'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa4daf41-5e72-42f1-bc46-1793cb513efd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 591c7e56-0049-43dc-afa7-2b04119eb9fe
        userCondition: null
handle: fd_st_dataTablesBlock
hasTitleField: false
icon: null
name: 'Data Tables Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
