fieldLayouts:
  9306c541-12e7-497e-a786-5823b4358ad8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 876b0d71-d0a3-4466-992a-c4d4e853489b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90255920-387f-4c37-97b0-b86cb87c6508 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fe72622-d022-44b9-9206-543147c34120
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91348804-4146-486b-8d4f-477165c1ff89
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7acd5d39-6c1f-40f8-add1-7d3ff114c820 # Meta Title (if different from page title)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67468ab5-d3f9-4103-8850-6f994e8bb516
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d5aae72-d3da-4be6-810d-6382928dd1fe # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81f323d1-b185-4800-84fb-25fce29513b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e2808b9-d312-4282-8380-7b1d3f248e8b # Meta OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e360c05e-a7dc-4a85-a109-f850c5226360
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3f4ab15-88ea-4329-baa2-46cbe0eacca8 # Meta OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 726cbbfa-209e-46d5-9133-8c4c43a44ad3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf4a664b-f40f-4d66-b727-a4ec3378e188 # Meta Twitter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cc49c03-a0e4-4ca8-a51a-78aa396d9606
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37064180-6b3f-4c01-994d-58da67c146c0 # Meta Twitter Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c41a9339-69fa-41e3-b761-45c80df5a7b1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8dbc2f9d-f3c0-4441-8a8d-ff4561f93ec3
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
