color: null
description: null
fieldLayouts:
  330da277-ce8e-4180-b284-6075290f586f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: de6f38a7-4a16-4ec5-8f08-d8389d3308a5
            handle: null
            includeInCards: false
            instructions: null
            label: 'Data Table'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6559eaf9-2fa4-47a4-9c1b-d0e0a7d62301
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c423afc7-9198-4da6-afe4-b3a8780e38ad
        userCondition: null
handle: itemDataTable
hasTitleField: false
icon: null
name: 'Item Data Table'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
