fieldLayouts:
  40bc63ad-6741-4d97-a71f-9c429319e1e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Product Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e36250a6-c881-4320-a8a8-03dcef3b5b65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1e3075d-9f29-4a10-b387-766c0978695e # Product Individual Short Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5285822-89a7-4ee8-8c03-eed15c71adee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d51174c-6c6f-4597-8a52-11035f32ae52 # Application Suitability
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd9c8a92-ffa0-4fe2-b6dc-648ad482e437
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a99d1f89-fb8c-4a25-9962-0c5a2f509cb0 # Fan Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6d54466-bb5c-446f-b4ea-52b67e633735
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 200e453b-bd54-4f36-a1b6-2f21913fd5cc # Fan Tech Drawing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d979bac-4c95-46d8-9750-1ee7cdcf5fef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a144cfc8-52eb-426f-a3f5-a5f34f09c5eb # Positioning
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86327ea0-3f53-4095-b430-408b835bd4b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74469b66-90dd-438f-a2da-29850fd9c882 # Costruction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e657cdd2-ed1a-44d0-94a3-528ee5fdc22f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7db1fcdc-70a2-4533-a781-1b7fefd6f0be # Data Tables
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0bae770-bc8f-4d03-8753-06252069f529
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a40cfae-6b78-41a5-9f4c-c567bd9d9c71 # Special Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56ee4ccf-3760-40f5-88b6-a12203812508
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ab76088-96ec-4c9c-a405-992253d0a248 # Data Sheet Option
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbe85fbf-47ef-46ac-a523-0c6d865d1d63
            userCondition: null
            warning: null
            width: 100
        name: 'Product Information'
        uid: c033ddce-f7cc-4d9d-80c7-faa592761395
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7acd5d39-6c1f-40f8-add1-7d3ff114c820 # Meta Title (if different from page title)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 631534a2-e6ef-460c-b88b-b9f39a49b4e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d5aae72-d3da-4be6-810d-6382928dd1fe # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59ba22c4-08b6-4afd-aabe-5fa706782027
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e2808b9-d312-4282-8380-7b1d3f248e8b # Meta OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9690d7b0-721b-49fb-b444-7a7636ea9fe0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3f4ab15-88ea-4329-baa2-46cbe0eacca8 # Meta OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b46c954-914c-47df-85e9-073a17b1b1e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf4a664b-f40f-4d66-b727-a4ec3378e188 # Meta Twitter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0894f0ff-c153-454f-ac49-32b2cfb9a8b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37064180-6b3f-4c01-994d-58da67c146c0 # Meta Twitter Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06afa9a6-7668-4280-9690-583bf34bee2e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9cd690dd-bd65-4fd7-a389-678413c60a6a
        userCondition: null
handle: secType_productSpecification
hasTitleField: true
name: 'Product Specification'
section: c2f1f492-f8d4-42ba-ac19-6fc8ef262ebb # Product Specifications
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
