fieldLayouts:
  81fa309a-a312-45fa-927c-7b0359cb0aed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Product Group Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1edaea8d-637e-4bd0-a936-9f424a4cc47b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1bee32c2-e2ab-4583-b625-6eb82f37a359 # Product Global Short introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7a880cc-bdc6-4b1b-a518-9206b2131920
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2a97afa9-53a0-4d80-a84c-ce50b7d3a88d # Product Group Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faecd047-2c55-4033-8e3d-752e94288f1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36bc5ee4-9df2-4699-b1a7-06b6ed9b2bd9 # Product Group Global Specifications
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b78da2a3-3f25-4b8f-b5f6-59483b3ca8d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02cdf417-bd93-4fa2-ab02-8b5b0240abe6 # Additional Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb227e30-61cf-45ea-87fb-b3940884dfce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ab76088-96ec-4c9c-a405-992253d0a248 # Data Sheet Option
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2f19b18-cb66-4ba4-bd7d-6d8e5ec6e689
            userCondition: null
            warning: null
            width: 100
        name: 'Group Introduction'
        uid: ef9032ba-b7dd-4892-abde-0d80e241b051
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7acd5d39-6c1f-40f8-add1-7d3ff114c820 # Meta Title (if different from page title)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17298406-0433-4950-94ef-dacdcca7d2cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d5aae72-d3da-4be6-810d-6382928dd1fe # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 820f30b0-8309-4e17-adae-b164900df692
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e2808b9-d312-4282-8380-7b1d3f248e8b # Meta OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77fa9a70-34e8-4c95-8ae0-602579da0a72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3f4ab15-88ea-4329-baa2-46cbe0eacca8 # Meta OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef8f02fa-974f-4d16-ae10-1735bc0ed4d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf4a664b-f40f-4d66-b727-a4ec3378e188 # Meta Twitter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3931d1ee-f784-4e57-b312-21a02bfb70ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37064180-6b3f-4c01-994d-58da67c146c0 # Meta Twitter Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dcf30b3-2ae0-4751-8d7a-64be4d890e84
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: f843d8bf-e99c-4daa-b3f5-8d731768797b
        userCondition: null
handle: secType_productGroupOverview
hasTitleField: true
name: 'Product Group Overview'
section: c2f1f492-f8d4-42ba-ac19-6fc8ef262ebb # Product Specifications
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
