defaultPlacement: end
fieldLayouts:
  b9bb5b54-5610-41a2-95dc-792dd2895773:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: cb0827ac-51b5-4960-affe-5fa6a840d33c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6001e521-374a-430a-92be-70b6c6ceb1c4 # Category Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1187593d-4130-4466-bbcd-0790af093a07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36bc5ee4-9df2-4699-b1a7-06b6ed9b2bd9 # Product Group Global Specifications
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa5792f9-daf7-478e-96fc-2e01c7d00aa7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9767d245-69a9-444d-89ad-63c08cceeb3f # Ancilliary Item Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d3471e2-29c7-4abf-a008-4c4138471ab2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d69ec146-f7fb-4227-a152-5be9f01b6264 # Suitable Fans
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d83334d7-ec2a-4c0b-8848-3b89244dac7e
            userCondition: null
            warning: null
            width: 100
        name: 'Category Overview'
        uid: e87d0850-ad68-43e9-9294-ebcf5ab85f86
        userCondition: null
handle: catGrp_productApplication
name: 'Product Application'
siteSettings:
  33f09b38-742d-44f8-a75d-188811b9c44b: # Victoria Fans (en)
    hasUrls: true
    template: by_application
    uriFormat: '{% if object.level == 1 %}fans-by-application/{slug}{% else %}{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 45c016d3-252f-47b9-bf34-413f81cf7c38
