fieldLayouts:
  f4f603c9-04cf-4a29-81c1-4a8bc533b19a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fc3ec53a-0134-41c7-af9c-77df90ce8f87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8dc08318-3140-4452-97ab-2876b0c375d7
        userCondition: null
fs: drawings
handle: drawings
name: Drawings
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
