fieldLayouts:
  cd89f535-7c72-404a-988f-201d31692f45:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 01e02a6b-d870-4a82-bc74-f8280bd338fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b64a4b0-9623-4ea0-998e-f7623fcbd14c
        userCondition: null
fs: fans
handle: fans
name: Fans
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
