fieldLayouts:
  3d57b857-70b1-4f5a-9e04-08898503c8d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2bcd1c6e-d275-45f7-8846-5913d0fe3b59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: afac8fd9-22e3-4851-8a6a-59246209ba2c
        userCondition: null
fs: general
handle: general
name: General
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
