fieldLayouts:
  bce7f721-7d47-4967-88bf-7b5daaad51ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0389457d-e78e-41b4-9101-7c3c9cc96164
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c5758bd-f9d7-4a63-aa1b-27769db8da01
        userCondition: null
fs: userPhotos
handle: userPhotos
name: 'User Photos'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
