columnSuffix: null
contentColumnType: string
fieldGroup: 974928bb-eb6a-4e46-8103-487ab15e4c66 # Default
handle: body
instructions: null
name: Body
searchable: true
settings:
  ckeConfig: d1ac3d29-9bab-418a-8f28-3855680f77ca # Standard
  columnType: text
  enableSourceEditingForNonAdmins: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
