columnSuffix: null
contentColumnType: string
handle: dataSheetOption
instructions: null
name: 'Data Sheet Option'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Show download option?'
        -
          - value
          - showDownloadOption
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
