columnSuffix: null
contentColumnType: string
handle: fd_additionalOptions
instructions: null
name: 'Additional Options'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 58
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 59
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new1
        -
          __assoc__:
            -
              - width
              - ''
  entryTypes:
    - 47a69ae8-eeea-477b-a541-124c1a5cfc6a # Additional Options Block
  fieldLayout: row
  maxEntries: null
  maxRows: null
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add further information'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
