columnSuffix: null
contentColumnType: string
fieldGroup: 80829250-34bf-44e3-873e-30fd538a844e # Product Information
handle: fd_additionalOptions
instructions: null
name: 'Additional Options'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 58
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 59
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new1
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%supertablecontent_fd_additionaloptions}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add further information'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
