columnSuffix: null
contentColumnType: string
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_costruction
instructions: null
name: Costruction
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    14:
      __assoc__:
        -
          - width
          - ''
    15:
      __assoc__:
        -
          - width
          - ''
  contentTable: ''
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add another component'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
