columnSuffix: null
contentColumnType: string
handle: fd_costruction
instructions: null
name: Costruction
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    14:
      __assoc__:
        -
          - width
          - ''
    15:
      __assoc__:
        -
          - width
          - ''
  entryTypes:
    - 31533fe2-23c1-4c59-98dd-15a1641153e4 # Costruction Block
  fieldLayout: row
  maxEntries: null
  maxRows: null
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add another component'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
