columnSuffix: null
contentColumnType: string
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_product_Individual_Short_Summary
instructions: null
name: 'Product Individual Short Summary'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: fd3fef83-fe9d-4015-9de7-a6c4efa2780e # Simple 2
  columnType: text
  enableSourceEditingForNonAdmins: false
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
