columnSuffix: null
contentColumnType: string
fieldGroup: 80829250-34bf-44e3-873e-30fd538a844e # Product Information
handle: fd_product_global_ShortIntroduction
instructions: null
name: 'Product Global Short introduction'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: fd3fef83-fe9d-4015-9de7-a6c4efa2780e # Simple 2
  columnType: text
  enableSourceEditingForNonAdmins: false
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
