columnSuffix: null
contentColumnType: text
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_positioning
instructions: null
name: Positioning
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
