columnSuffix: null
contentColumnType: string
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_st_dataTables
instructions: null
name: 'Data Tables'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    22:
      __assoc__:
        -
          - width
          - ''
  contentTable: '{{%supertablecontent_fd_st_datatables}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add another Data Table'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
