columnSuffix: null
contentColumnType: string
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_st_dataTables
instructions: null
name: 'Data Tables'
searchable: true
settings:
  errorMessage: 'Unable to find component class ''SuperTable''.'
  expectedType: SuperTable
  settings:
    __assoc__:
      0:
        - columns
        -
          22:
            __assoc__:
              -
                - width
                - ''
      1:
        - fieldLayout
        - row
      3:
        - selectionLabel
        - 'Add another Data Table'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
