columnSuffix: null
contentColumnType: string
handle: fd_st_specialNotes
instructions: null
name: 'Special Notes'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    17:
      __assoc__:
        -
          - width
          - ''
  entryTypes:
    - 5543734e-141e-41f4-ba94-04dddf8d2e87 # Special Notes Block
  fieldLayout: row
  maxEntries: null
  maxRows: null
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a note'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
