columnSuffix: null
contentColumnType: string
fieldGroup: e5a1e701-feac-4d3f-b9d9-e8b7f67468fc # Individual Product
handle: fd_st_specialNotes
instructions: null
name: 'Special Notes'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    17:
      __assoc__:
        -
          - width
          - ''
  contentTable: '{{%supertablecontent_fd_st_specialnotes}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a note'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
