columnSuffix: null
contentColumnType: string
handle: fd_st_dataTables
instructions: null
name: 'Data Tables'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    22:
      __assoc__:
        -
          - width
          - ''
  entryTypes:
    - 4344a890-9100-43bf-abfa-b163ecc712db # Data Tables Block
  fieldLayout: row
  maxEntries: null
  maxRows: null
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add another Data Table'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
