columnSuffix: null
contentColumnType: string
fieldGroup: 80829250-34bf-44e3-873e-30fd538a844e # Product Information
handle: fd_st_productGroupGlobalSpecifications
instructions: null
name: 'Product Group Global Specifications'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    5:
      __assoc__:
        -
          - width
          - ''
    6:
      __assoc__:
        -
          - width
          - ''
  contentTable: ''
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add more information'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
