columnSuffix: null
contentColumnType: text
fieldGroup: 80829250-34bf-44e3-873e-30fd538a844e # Product Information
handle: fd_specialNote
instructions: null
name: 'Special Note'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
