columnSuffix: null
contentColumnType: string
handle: fd_st_productGroupGlobalSpecifications
instructions: null
name: 'Product Group Global Specifications'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    5:
      __assoc__:
        -
          - width
          - ''
    6:
      __assoc__:
        -
          - width
          - ''
  entryTypes:
    - 3381a675-90f1-4cf2-924f-4ac2537c460b # Product Group Global Specifications Block
  fieldLayout: row
  maxEntries: null
  maxRows: null
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add more information'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
