columnSuffix: null
contentColumnType: string
fieldGroup: 9b094e3b-fb35-468c-9850-bad51e1f29e2 # Company Background
handle: secondaryText
instructions: null
name: 'Secondary Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 69ffc5cd-2c17-46ad-b49e-42706f0b9b1f # Default
  columnType: text
  enableSourceEditingForNonAdmins: false
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
