columnSuffix: null
contentColumnType: text
fieldGroup: 6283093f-5a13-4c50-a2f5-c15b598b383d # SEO
handle: seo_metaTitle
instructions: null
name: 'Meta Title (if different from page title)'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
