changedFieldIndicator: null
field: 6a40cfae-6b78-41a5-9f4c-c567bd9d9c71 # Special Notes
fieldLayouts:
  26cf4905-20da-4750-a196-f004708b4ad2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 851fbe84-b848-4787-a77c-34cf932039f4 # Note Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 738c4f8f-64f9-4177-8270-08a430d6b588
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37d05d25-9f02-4fa4-a442-783a579e27a7
        userCondition: null
fields:
  851fbe84-b848-4787-a77c-34cf932039f4: # Note Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fd_st_noteText
    instructions: null
    name: 'Note Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
