changedFieldIndicator: null
field: a77c9dcf-1b53-47f0-b94f-88b8dfcff3d5 # Add Additional Info
fieldLayouts:
  e48bdef6-4ad3-4ef7-99c1-0c1c03b378ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bcf4e0a6-3bfd-4723-9b4c-d5d40ed18f1a # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 812917ec-f838-4bf7-af62-f8726d37a2d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff8acaa1-9621-4ec7-8737-f747573a01df # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5ed148-e689-4254-ba5f-90795d42cde8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7068d81f-0364-43cb-a0e8-292b7e7a9bf0
        userCondition: null
fields:
  bcf4e0a6-3bfd-4723-9b4c-d5d40ed18f1a: # Header
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: null
    name: Header
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ff8acaa1-9621-4ec7-8737-f747573a01df: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
