fieldLayouts:
  5631850a-5206-494c-9b04-c2f5d7e1d322:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f2555abd-79e8-4614-a19c-950aa0f7955f # Global Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75578e87-3f78-4228-a40e-8d9ffb530483
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7bcdd120-af65-4abd-a00c-85ea451feeb8 # Global Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e26d9032-8940-48fd-bc41-19e90450ebee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acb6352f-f138-4d95-914c-ebea0af62985 # Global OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3dc8594-04de-48ee-8218-458de25a40fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94db20e8-0722-44ec-8556-a552e5a3ce8f # Global OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43667e90-0dc2-4a08-a3c6-33e3fcad9a0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a28a33b-2792-430c-b934-912a89f72155 # Global SEO Twitter Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f90d4f8e-42e0-403d-9fb6-5f21cbc3533d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce056006-53f7-4afd-b2d8-3c519ddf52ca # Global Twitter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76d50901-bf97-4b73-9ca1-9043a4876d08
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e798811d-5586-4b32-bd92-8179dc24cf6b # Global Twitter Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b545614e-ddb9-4a89-96b4-15ae01047476
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06876340-287f-406c-8a11-e0fd8bd442aa
        userCondition: null
handle: globalSeo
name: 'Global SEO'
sortOrder: 1
