defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3af3ad4e-3d45-44f3-bd52-035d079ec6c0 # Ancillaries
  -
    uid: 7ef2438b-9479-4872-8d4a-37f826ef3c27 # Product Group Overview
  -
    uid: 0221bae3-0c87-4976-b7f9-39a728c50154 # Product Specification
handle: productSpecifications
maxAuthors: 1
name: 'Product Specifications'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  33f09b38-742d-44f8-a75d-188811b9c44b: # Victoria Fans (en)
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: aeb45b34-33b3-43eb-9402-a4c2151bd931
type: structure
